language: go
go:
- 1.12.x
install:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
- go get github.com/golang/dep/cmd/dep
- dep ensure
script:
- golangci-lint run --disable-all --enable=vet --enable=ineffassign --enable=goconst --tests ./...
- go test -v -race ./...

before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"

deploy:
  - #goreleaser
    provider: script
    script: curl -sL https://git.io/goreleaser | bash
    skip_cleanup: true
    on:
      tags: true

after_deploy:
  - git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
  - bonsai/generate-sha512sum.sh
  - bonsai/github-release-upload.sh github_api_token=$GITHUB_TOKEN repo_slug="$TRAVIS_REPO_SLUG" tag="${TRAVIS_TAG}" filename="dist/$(cat dist/sha512_file)"

env:
  global:
    secure: ZqXJ47Pv2arpAbejggufO7PWoBeduT7YG9W/wML6Sq/wob8uPiG56KS4TAuyFVbzsj6qdM1AQqBQ+ta9JvCOCLLOXrLKdPnF0QN+t3IXCpAz0zYV9pz4SYn2XEuoUYiL7nPIUUWnG436NaEqBt01+jhjV39Bx3Mpi0YPinqcVW6u6FFHloFw0pWKytMap21BJLS74TAO/dhftgT9HmpY2iyqd2Ornp7++y9/oKYqB3Lv6o+EEj0FWmnD/ZP9zOUoNzzDRdNW+xGqKkkJleGawkuasm292kFXxK5dBCzGiq25t2UVIteWeJoEldtqMheHuXSP/HV7+zDOyt2IPLonAWZ2TXcYQ3R6nGyJw2G6fOAixCQrEO0ZJSlpRULM5Ou1O0feB0rdW+GYt3XAPBSaPrmIy0MGPEE1XRE66JHz4AVvuM76qxbH9gkF63bTujZr6FkhrN0t8Z6ExTx8BAN0KXK+kwKoDeILtAhcWL/mk6xkynlVj4GLQPZiZ/HZp62VXee3TOH1ZCWCNHyVrTEBSfGZCSr2A9u/O+ERPOBiQatT6HOXtCayKya/DurOTtLLKX484B+MZSby6wbwonFK0DsizFHqIxc/gtAbtIs7VJ+kf9kziuOkGfHAD2+ZYLr4ub8Q4MfZc6hOUqBLKFW3w4q8WyJ1l62vb+0wRiDzFoU=
